In [39]:
#import os
#os.system('sh marcap.sh')

!sh marcap.sh

Already up to date.

In [40]:

"""
# 
import subprocess
pwd = subprocess.Popen("pwd", shell=True, stdout=subprocess.PIPE).stdout
curr_dir = pwd.read().decode().rstrip()
curr_dir
"""

# extract filename and extension
import os
fullpath = '/Users/jkkim/workspace/python/stock/my/download/21_1Q_종합순위_220605_162809.xlsx'
directory = fullpath[:fullpath.rindex('/')]
filename, ext = os.path.splitext(os.path.basename(fullpath))

"""
import datetime
from marcap import marcap_data

yymmdd = filename.split('_')[-2]
next = datetime.datetime.strptime(yymmdd, '%y%m%d')
yyyymmdd = next.strftime('%Y-%m-%d')
result = marcap_data(yyyymmdd)
while len(result) <= 0:
    next = next + datetime.timedelta(days=-1)
    yyyymmdd = next.strftime('%Y-%m-%d')
    result = marcap_data(yyyymmdd)

#result
"""

import FinanceDataReader as fdr

krx = fdr.StockListing('KRX')
krx

,Symbol,Market,Name,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,060310,KOSDAQ,3S,전자부품 제조업,반도체 웨이퍼 캐리어,2002-04-23,03월,김세완,http://www.3sref.com,서울특별시
1,095570,KOSPI,AJ네트웍스,산업용 기계 및 장비 임대업,"렌탈(파렛트, OA장비, 건설장비)",2015-08-21,12월,"박대현, 손삼달",http://www.ajnet.co.kr,서울특별시
2,006840,KOSPI,AK홀딩스,기타 금융업,지주사업,1999-08-11,12월,"채형석, 이석주(각자 대표이사)",http://www.aekyunggroup.co.kr,서울특별시
3,054620,KOSDAQ,APS홀딩스,기타 금융업,인터넷 트래픽 솔루션,2001-12-04,12월,정기로,http://www.apsholdings.co.kr,경기도
4,265520,KOSDAQ,AP시스템,특수 목적용 기계 제조업,디스플레이 제조 장비,2017-04-07,12월,김영주,http://www.apsystems.co.kr,경기도
...,...,...,...,...,...,...,...,...,...,...
7819,003280,KOSPI,흥아해운,해상 운송업,외항화물운송업(케미컬탱커),1976-06-29,12월,이환구,http://www.heung-a.com,서울특별시
7820,037440,KOSDAQ,희림,"건축기술, 엔지니어링 및 관련 기술 서비스업",설계 및 감리용역,2000-02-03,12월,"정영균, 이목운, 허철호 (각자대표)",http://www.heerim.com,서울특별시
7821,419890,KOSPI,히어로즈 단기채권ESG액티브,NaN,NaN,NaT,NaN,NaN,NaN,NaN
7822,429870,KOSPI,히어로즈 리츠이지스액티브,NaN,NaN,NaT,NaN,NaN,NaN,NaN
7823,238490,KOSDAQ,힘스,특수 목적용 기계 제조업,"OLED Mask 인장기, OLED Mask 검사기 등",2017-07-20,12월,김주환,http://www.hims.co.kr,인천광역시

In [41]:
import pandas as pd
old = pd.read_excel(fullpath)
old

# modify table (add column,...)

# overwrite the file

#import os
#import datetime
#from my.utils import ( format_time_from_seconds )

#curr_dir = os.path.dirname(os.path.abspath(__file__))

,Unnamed: 0,종목코드,종목명,기준일,시가총액,상장주식수,매출액(수익),매출총이익,영업이익,당기순이익,...,1/PER 순위,1/PBR,1/PBR 순위,1/PCR,1/PCR 순위,1/PSR,1/PSR 순위,종합 순위,NCAV,NCAV 순위
0,37,17940,E1,2021-04-01,295666000000,6860000,12626.064400,919.502220,370.838930,426.747370,...,63.0,4.898359,5.0,0.714393,45.0,13.453518,11.0,1.0,-3.665351,1998.0
1,815,4690,삼천리,2021-04-01,317913960000,4055025,11971.357170,1552.150710,744.459620,647.279050,...,117.0,4.978592,4.0,0.641886,53.0,10.194719,26.0,2.0,-3.632100,1996.0
2,25,16610,DB금융투자,2021-04-01,257649581230,42446389,NaN,NaN,591.377763,448.793309,...,12.0,3.319722,38.0,0.584409,67.0,5.429766,100.0,3.0,NaN,NaN
3,214,267290,경동도시가스,2021-04-01,116434268500,5895406,4565.974837,377.362033,166.144588,132.837828,...,86.0,3.150698,50.0,0.641531,54.0,9.788567,29.0,4.0,-0.039185,1339.0
4,2062,88350,한화생명,2021-04-01,2727184200000,868530000,NaN,NaN,4367.018389,3363.913286,...,154.0,4.645113,8.0,0.972375,21.0,8.999280,37.0,5.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2137,2068,340440,한화플러스제1호스팩,2021-04-01,9749700000,4710000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2138,2070,34810,해성산업,2021-04-01,426972027600,26356298,2511.794150,430.851610,149.538820,463.167130,...,NaN,1.831737,226.0,NaN,NaN,NaN,NaN,NaN,-0.244104,1601.0
2139,2085,319400,현대무벡스,2021-04-01,463345185820,101722324,399.222705,59.951543,1.458891,-34.198965,...,NaN,0.240734,1815.0,NaN,NaN,NaN,NaN,NaN,0.109561,874.0
2140,2117,378850,화승알앤에이,2021-04-01,104274990270,18993623,632.080066,104.302256,32.806674,32.367272,...,NaN,0.518783,1254.0,NaN,NaN,NaN,NaN,NaN,-1.527290,1924.0
2141,2159,238490,힘스,2021-04-01,151583962400,11312236,105.638493,22.828579,-18.824890,-1.472019,...,NaN,0.505924,1281.0,NaN,NaN,NaN,NaN,NaN,0.220068,558.0